### PR TITLE
GUI 3.0

### PR DESCRIPTION
**Pull request by The-Sizzler**

### CODE REVIEW

**Comment by arlinsandbulte** [comment]
Looks like this reverts some changes I made recently.  Probably need to pull in my recent changes &/or rebase some things.
Also, I'm not overly fond of needing to add tkmacosx just for the update notification button (right?).
Could we do something different there?

**Comment by The-Sizzler** [comment]
Updated the code to match the most recent...

[tkmacosx](https://pypi.org/project/tkmacosx/) is very popular and is used pretty often since tkinter is fairly limiting when it comes to mac customization.
if you don’t want to use it I can try to use a label instead of a button or just remove the red

**Comment by arlinsandbulte** [comment]
Let's just remove the background color.
Another option might be to use an image link instead... but I prefer the button.  At least to start.

**Comment by The-Sizzler** [comment]
Pull request has been updated. Should be good to go.

**Pull request merged**
